krud-dev/ostara

- .changeset/tiny-seahorses-wash.md
- src/renderer/components/managers/GoogleAnalyticsManager.tsx
> feat: add anonymizeIp to ReactGA

- .changeset/itchy-hats-share.md
- src/renderer/apis/requests/instance/thread-profiling/getInstanceThreadProfilingRequests.ts
- src/renderer/apis/websockets/stompTopics.ts
- src/renderer/components/table/data/TableCellDataCustomText.tsx
- src/renderer/components/table/data/TableCellDataLabel.tsx
- src/renderer/entity/entities/instanceThreadProfilingRequest.entity.tsx
- src/renderer/entity/entity.d.ts
- src/renderer/lang/locales/en_US.ts
- src/renderer/pages/navigator/instance/threaddumps/index.tsx
> feat: add thread profiling ws updates

- .changeset/modern-gifts-reflect.md
- src/renderer/pages/navigator/instance/http-requests/components/InstanceHttpRequestDetails.tsx
> fix: http requests statistics spinner not showing

- .changeset/six-seahorses-raise.md
- src/renderer/layout/common/main-sidebar/MainNavbar.tsx
- src/renderer/layout/common/main-sidebar/navbar/HelpMenu.tsx
- src/renderer/routes/urls.ts
> feat: add help button

- daemon/src/main/kotlin/dev/krud/boost/daemon/threadprofiling/ThreadProfilingService.kt
> fix: fix thread profiling event updates

- .changeset/itchy-geckos-report.md
- assets/splash.html
- src/renderer/lang/locales/en_US.ts
- src/renderer/layout/common/main-sidebar/navbar/SettingsMenu.tsx
> feat: add app version to splash and settings

- daemon/src/main/kotlin/dev/krud/boost/daemon/configuration/application/ApplicationService.kt
- daemon/src/main/kotlin/dev/krud/boost/daemon/controller/api/v1/application/ApplicationAbilityController.kt
- daemon/src/test/kotlin/dev/krud/boost/daemon/configuration/application/ApplicationServiceTest.kt
- daemon/src/test/kotlin/dev/krud/boost/daemon/configuration/application/_stubs.kt
- daemon/src/test/kotlin/dev/krud/boost/daemon/configuration/instance/_stubs.kt
- daemon/src/test/kotlin/dev/krud/boost/daemon/controller/api/v1/application/ApplicationAbilityControllerTest.kt
- daemon/src/test/kotlin/dev/krud/boost/daemon/test/TestKrud.kt
> feat: add endpoint to retrieve application abilities

- .changeset/tall-bats-grow.md
- src/renderer/components/common/ToolbarButton.tsx
- src/renderer/components/table/TableRowCustom.tsx
- src/renderer/components/table/TableSelectedActions.tsx
- src/renderer/components/table/TableToolbar.tsx
- src/renderer/pages/navigator/application/loggers/index.tsx
- src/renderer/pages/navigator/instance/caches/index.tsx
- src/renderer/pages/navigator/instance/environment/index.tsx
- src/renderer/pages/navigator/instance/loggers/index.tsx
- src/renderer/pages/navigator/instance/system-environment/index.tsx
- src/renderer/pages/navigator/instance/system-properties/index.tsx
> fix: disable table action buttons while loading 

- .changeset/lovely-mirrors-share.md
- src/renderer/pages/navigator/instance/threaddumps/contexts/ThreadLogContext.tsx
> fix: thread profiling cell click opens multiple details boxes 

- .changeset/tough-beans-battle.md
- src/renderer/components/common/ToolbarButton.tsx
- src/renderer/components/dialog/DialogTitleEnhanced.tsx
- src/renderer/components/item/cache/ItemCacheStatisticsDialog.tsx
- src/renderer/components/table/TableHeadCustom.tsx
- src/renderer/components/table/TableRowCustom.tsx
- src/renderer/components/table/TableSelectedActions.tsx
- src/renderer/components/table/TableToolbar.tsx
- src/renderer/constants/ui.ts
- src/renderer/entity/entities/applicationCache.entity.tsx
- src/renderer/entity/entities/instanceCache.entity.tsx
- src/renderer/entity/entities/instanceHeapdumpReferences.entity.tsx
- src/renderer/entity/entities/instanceThreadProfilingRequest.entity.tsx
- src/renderer/entity/entity.d.ts
- src/renderer/lang/locales/en_US.ts
- src/renderer/pages/navigator/instance/threaddumps/components/ThreadLogDetails.tsx
- src/renderer/pages/navigator/instance/threaddumps/components/ThreadProfilingRequestDetailsDialog.tsx
> feat: add explanation for disabled table row actions

- .changeset/sweet-teachers-yell.md
- src/renderer/contexts/UiContext.tsx
- src/renderer/lang/locales/en_US.ts
- src/renderer/layout/common/main-sidebar/navbar/SettingsMenu.tsx
- src/renderer/theme/overrides/Alert.tsx
> feat: add ability to control error reporting 

- .changeset/little-seahorses-occur.md
- src/renderer/apis/requests/application/caches/getApplicationCaches.ts
- src/renderer/apis/requests/instance/caches/getInstanceCaches.ts
- src/renderer/apis/requests/item/getItemAbilities.ts
- src/renderer/contexts/NavigatorTreeContext.tsx
- src/renderer/layout/application/ApplicationLayout.tsx
- src/renderer/layout/application/components/ApplicationSidebar.tsx
- src/renderer/layout/instance/InstanceLayout.tsx
- src/renderer/layout/instance/components/InstanceSidebar.tsx
- src/renderer/pages/navigator/application/caches/index.tsx
- src/renderer/pages/navigator/instance/caches/index.tsx
- src/renderer/routes/guards/AbilityGuard.tsx
- src/renderer/routes/routes.tsx
> feat: add item abilities polling and guard

- .changeset/neat-berries-pay.md
- src/infra/autoupdate/appUpdater.ts
- src/infra/store/store.ts
- src/main/main.ts
Change the scheduled job to every 5 minutes, and persist the last check to ensure a check is done at least once an hour
> feat: change auto update check frequency

- .changeset/eighty-mangos-worry.md
- src/renderer/components/common/ToolbarButton.tsx
- src/renderer/components/table/details/DetailsLabelValueHorizontal.tsx
- src/renderer/pages/navigator/instance/threaddumps/components/ThreadLogDetails.tsx
- src/renderer/pages/navigator/instance/threaddumps/components/ThreadLogsBar.tsx
> fix: thread profiling thread data card ui

- .changeset/stupid-queens-attack.md
- src/renderer/components/item/dialogs/forms/ApplicationDetailsForm.tsx
- src/renderer/components/item/dialogs/forms/FolderDetailsForm.tsx
- src/renderer/components/item/dialogs/forms/InstanceDetailsForm.tsx
- src/renderer/components/item/dialogs/forms/fields/ItemIconFormField.tsx
- src/renderer/lang/locales/en_US.ts
> fix: update item icon ui

- .changeset/violet-trees-punch.md
- daemon/src/main/kotlin/dev/krud/boost/daemon/configuration/instance/httprequeststatistics/InstanceHttpRequestStatisticsService.kt
- daemon/src/main/kotlin/dev/krud/boost/daemon/controller/api/v1/instance/InstanceHttpRequestStatisticsController.kt
- daemon/src/test/kotlin/dev/krud/boost/daemon/configuration/instance/httprequeststatistics/InstanceHttpRequestStatisticsServiceTest.kt
- src/renderer/apis/requests/instance/http-requests/getInstanceHttpRequestStatisticsForUriByStatuses.ts
- src/renderer/pages/navigator/instance/http-requests/components/InstanceHttpRequestDetails.tsx
> fix: http request statistics - change key of statuses to string

- .changeset/shiny-bikes-serve.md
- daemon/src/main/kotlin/dev/krud/boost/daemon/actuator/model/MappingsActuatorResponse.kt
- src/common/generated_definitions.d.ts
> fix: make dispatcherServlets nullable in mappings

- .changeset/nine-ears-arrive.md
- src/infra/rendererUtils/main.ts
- src/infra/rendererUtils/renderer.ts
- src/infra/rendererUtils/types.d.ts
- src/renderer/components/item/dialogs/create/CreateInstanceDialog.tsx
- src/renderer/components/item/dialogs/forms/InstanceDetailsForm.tsx
> feat: create instance form default actuator url from clipboard

- .changeset/ninety-fishes-kneel.md
- src/renderer/constants/regex.ts
> fix: url regex not allowing dashes

- .changeset/light-bottles-guess.md
- src/renderer/layout/navigator/components/sidebar/tree/NavigatorTreeNode.tsx
> fix: navigator instance tooltip open while dragging

- .changeset/yellow-mice-rescue.md
- src/renderer/constants/regex.ts
> fix: url regex path allowed characters

- .changeset/beige-ligers-flash.md
- src/renderer/components/table/TableComponent.tsx
- src/renderer/components/table/TableContext.tsx
- src/renderer/components/table/TableNoData.tsx
- src/renderer/lang/locales/en_US.ts
- src/renderer/pages/navigator/instance/heapdumps/index.tsx
- src/renderer/pages/navigator/instance/threaddumps/index.tsx
> feat: add empty state to thread/heap dump tables

- .changeset/light-melons-roll.md
- src/renderer/components/help/EmptyContent.tsx
- src/renderer/components/item/logger/LogLevelToggleGroup.tsx
- src/renderer/components/table/data/custom/TableCellDataApplicationLoggerLevel.tsx
- src/renderer/components/table/data/custom/TableCellDataInstanceLoggerLevel.tsx
- src/renderer/theme/overrides/Progress.ts
> feat: add loading state to log level toggle

- .changeset/tough-plums-tell.md
- src/renderer/apis/requests/instance/env/getInstanceSystemEnvironment.ts
- src/renderer/apis/requests/instance/env/getInstanceSystemProperties.ts
- src/renderer/components/help/RedactionAlert.tsx
- src/renderer/constants/ui.ts
- src/renderer/hooks/useRerenderKey.ts
- src/renderer/lang/locales/en_US.ts
- src/renderer/pages/navigator/instance/properties/index.tsx
- src/renderer/pages/navigator/instance/system-environment/index.tsx
- src/renderer/pages/navigator/instance/system-properties/index.tsx
> feat: add redaction warning for masked actuator response

- .changeset/late-mails-repeat.md
- daemon/src/main/kotlin/dev/krud/boost/daemon/actuator/model/BeansActuatorResponse.kt
- daemon/src/main/kotlin/dev/krud/boost/daemon/actuator/model/CacheActuatorResponse.kt
- daemon/src/main/kotlin/dev/krud/boost/daemon/actuator/model/CachesActuatorResponse.kt
- daemon/src/main/kotlin/dev/krud/boost/daemon/actuator/model/ConfigPropsActuatorResponse.kt
- daemon/src/main/kotlin/dev/krud/boost/daemon/actuator/model/EndpointsActuatorResponse.kt
- daemon/src/main/kotlin/dev/krud/boost/daemon/actuator/model/EnvActuatorResponse.kt
- daemon/src/main/kotlin/dev/krud/boost/daemon/actuator/model/EnvPropertyActuatorResponse.kt
- daemon/src/main/kotlin/dev/krud/boost/daemon/actuator/model/FlywayActuatorResponse.kt
- daemon/src/main/kotlin/dev/krud/boost/daemon/actuator/model/HealthActuatorResponse.kt
- daemon/src/main/kotlin/dev/krud/boost/daemon/actuator/model/InfoActuatorResponse.kt
- daemon/src/main/kotlin/dev/krud/boost/daemon/actuator/model/IntegrationGraphActuatorResponse.kt
- daemon/src/main/kotlin/dev/krud/boost/daemon/actuator/model/LiquibaseActuatorResponse.kt
- daemon/src/main/kotlin/dev/krud/boost/daemon/actuator/model/LoggerActuatorResponse.kt
- daemon/src/main/kotlin/dev/krud/boost/daemon/actuator/model/LoggersActuatorResponse.kt
- daemon/src/main/kotlin/dev/krud/boost/daemon/actuator/model/MappingsActuatorResponse.kt
- daemon/src/main/kotlin/dev/krud/boost/daemon/actuator/model/MetricActuatorResponse.kt
- daemon/src/main/kotlin/dev/krud/boost/daemon/actuator/model/MetricsActuatorResponse.kt
- daemon/src/main/kotlin/dev/krud/boost/daemon/actuator/model/QuartzActuatorResponse.kt
- daemon/src/main/kotlin/dev/krud/boost/daemon/actuator/model/QuartzJobResponse.kt
- daemon/src/main/kotlin/dev/krud/boost/daemon/actuator/model/QuartzJobsByGroupResponse.kt
- daemon/src/main/kotlin/dev/krud/boost/daemon/actuator/model/QuartzJobsResponse.kt
- daemon/src/main/kotlin/dev/krud/boost/daemon/actuator/model/QuartzTriggerResponse.kt
- daemon/src/main/kotlin/dev/krud/boost/daemon/actuator/model/QuartzTriggersByGroupResponse.kt
- daemon/src/main/kotlin/dev/krud/boost/daemon/actuator/model/QuartzTriggersResponse.kt
- daemon/src/main/kotlin/dev/krud/boost/daemon/actuator/model/ScheduledTasksActuatorResponse.kt
- daemon/src/main/kotlin/dev/krud/boost/daemon/actuator/model/ThreadDumpActuatorResponse.kt
- daemon/src/main/kotlin/dev/krud/boost/daemon/utils/TypeDefaults.kt
> fix: add default values to all actuator responses

- .changeset/heavy-turtles-sin.md
- .changeset/hot-bulldogs-type.md
- .changeset/mean-apes-mate.md
- CHANGELOG.md
- package-lock.json
- package.json
- release/app/package-lock.json
- release/app/package.json
Releases:
@krud-dev/boost@0.7.0
> RELEASING: Releasing 1 package(s)

- .changeset/old-ways-suffer.md
- src/renderer/components/table/TableRowCustom.tsx
- src/renderer/components/table/details/DetailsLabelValueHorizontal.tsx
- src/renderer/components/table/details/DetailsLabelValueVertical.tsx
- src/renderer/entity/entities/instanceBean.entity.ts
> fix: grid text line break mid-word

- .changeset/shy-bags-train.md
- src/renderer/pages/navigator/instance/properties/components/InstancePropertiesCode.tsx
> feat: deep sort app properties keys alphabetically

- .changeset/pink-moose-punch.md
- daemon/src/main/kotlin/dev/krud/boost/daemon/actuator/ActuatorHttpClientImpl.kt
- daemon/src/main/kotlin/dev/krud/boost/daemon/configuration/application/ApplicationService.kt
- daemon/src/main/kotlin/dev/krud/boost/daemon/configuration/application/crud/ApplicationPersistentHooks.kt
- daemon/src/main/kotlin/dev/krud/boost/daemon/configuration/application/entity/Application.kt
- daemon/src/main/kotlin/dev/krud/boost/daemon/configuration/application/listeners/ApplicationAuthenticationListener.kt
- daemon/src/main/kotlin/dev/krud/boost/daemon/configuration/application/messaging/ApplicationDisableSslVerificationChangedMessage.kt
- daemon/src/main/kotlin/dev/krud/boost/daemon/configuration/application/ro/ApplicationModifyRequestRO.kt
- daemon/src/main/kotlin/dev/krud/boost/daemon/configuration/application/ro/ApplicationRO.kt
- daemon/src/main/kotlin/dev/krud/boost/daemon/configuration/instance/InstanceActuatorClientProvider.kt
- daemon/src/main/kotlin/dev/krud/boost/daemon/configuration/instance/InstanceActuatorClientProviderImpl.kt
- daemon/src/main/kotlin/dev/krud/boost/daemon/controller/api/v1/ActuatorController.kt
- daemon/src/main/resources/application.yml
- daemon/src/main/resources/db/migration/V20230516103511__Add_disable_SSL_verification_to_application.sql
- daemon/src/test/kotlin/dev/krud/boost/daemon/actuator/ActuatorHttpClientTest.kt
- daemon/src/test/kotlin/dev/krud/boost/daemon/configuration/application/ApplicationServiceTest.kt
- daemon/src/test/kotlin/dev/krud/boost/daemon/configuration/instance/TestInstanceActuatorClientProvider.kt
- src/common/generated_definitions.d.ts
- src/renderer/apis/requests/actuator/testConnectionByUrl.ts
- src/renderer/components/item/dialogs/create/CreateInstanceDialog.tsx
- src/renderer/components/item/dialogs/forms/ApplicationDetailsForm.tsx
- src/renderer/components/item/dialogs/forms/InstanceDetailsForm.tsx
- src/renderer/lang/locales/en_US.ts
- src/renderer/layout/instance/components/health/InstanceUnreachable.tsx
Closes #415, Closes #390, Closes #413
> Add ability to disable SSL verification

- .changeset/sweet-ravens-smoke.md
- src/renderer/components/item/authentication/forms/AuthenticationDetailsForm.tsx
- src/renderer/components/managers/AnalyticsEventsManager.tsx
- src/renderer/hooks/demo/useRestartDemo.ts
- src/renderer/hooks/demo/useStartDemo.ts
- src/renderer/hooks/demo/useStopDemo.ts
> feat: add analytics heartbeat and additional demo events

- .changeset/nervous-monkeys-confess.md
- src/renderer/components/widget/card/CountdownDashboardWidget.tsx
- src/renderer/components/widget/card/DashboardGenericCard.tsx
- src/renderer/components/widget/card/DataBarDashboardWidget.tsx
- src/renderer/components/widget/card/PercentCircleDashboardWidget.tsx
- src/renderer/components/widget/card/ProgressCircleDashboardWidget.tsx
- src/renderer/components/widget/card/StackedTimelineDashboardWidget.tsx
- src/renderer/components/widget/hooks/useWidgetErrorMetrics.tsx
- src/renderer/components/widget/hooks/useWidgetSubscribeToMetrics.ts
- src/renderer/lang/locales/en_US.ts
> fix: dashboard metric error handling

- .changeset/rotten-lions-trade.md
- src/renderer/hooks/demo/useStartDemo.ts
> fix: demo created multiple times

- .changeset/new-poems-provide.md
- app/src/renderer/layout/navigator/components/sidebar/tree/NavigatorTree.tsx
> fix: remove ability to move instances between applications

- .changeset/young-toys-behave.md
- app/src/renderer/components/table/TableContext.tsx
- app/src/renderer/lang/locales/en_US.ts
> fix: beans table dependency click not working when filtered

- LICENSE
- README.md
https://github.com/krud-dev/ostara/issues/462
> Fixing Apache-2.0 licensing for parsing

- .changeset/eighty-terms-love.md
- app/src/infra/notifications/models/notificationInfo.ts
- app/src/infra/notifications/notificationsService.ts
- app/src/renderer/components/managers/NotificationsManager.tsx
- app/src/renderer/contexts/SettingsContext.tsx
- app/src/renderer/lang/locales/en_US.ts
- app/src/renderer/layout/common/main-sidebar/navbar/SettingsMenu.tsx
- app/src/renderer/pages/navigator/home/components/HomeDeveloperMode.tsx
> feat: add notifications settings

- app/src/renderer/layout/common/main-sidebar/navbar/SettingsMenu.tsx
> fix: hide notifications sound from settings if notifications are inactive

- app/src/renderer/pages/navigator/application/dashboard/index.tsx
- app/src/renderer/pages/navigator/folder/dashboard/index.tsx
> fix: folder/application dashboards sorting by tree order

- app/src/renderer/components/managers/NotificationsManager.tsx
- app/src/renderer/entity/entities/applicationMetricRule.entity.tsx
- app/src/renderer/lang/locales/en_US.ts
- app/src/renderer/pages/navigator/application/metric-rules/components/MetricRuleDetailsForm.tsx
- app/src/renderer/pages/navigator/application/metric-rules/components/MetricRuleFormula.tsx
- app/src/renderer/pages/navigator/application/metric-rules/components/MetricSelectionForm.tsx
- app/src/renderer/pages/navigator/instance/metrics/components/MetricDetails.tsx
- app/src/renderer/pages/navigator/instance/metrics/components/MetricDetailsTags.tsx
- app/src/renderer/utils/metricUtils.ts
> fix: metric and metric rules fixes and improvements

- .changeset/thick-kangaroos-kneel.md
- app/src/renderer/pages/navigator/application/dashboard/index.tsx
- app/src/renderer/pages/navigator/application/instances/index.tsx
- app/src/renderer/pages/navigator/folder/applications/index.tsx
> feat: improve folder-applications and application-instances tables empty states

- app/src/infra/notifications/main.ts
- app/src/infra/notifications/notificationsService.ts
- app/src/infra/notifications/renderer.ts
- app/src/infra/notifications/types.d.ts
- app/src/renderer/lang/locales/en_US.ts
- app/src/renderer/layout/common/main-sidebar/navbar/SettingsMenu.tsx
> feat: add hint to open os notification settings

- .changeset/seven-rings-occur.md
- app/src/renderer/pages/navigator/instance/metrics/components/MetricDetailsMeasurements.tsx
- app/src/renderer/utils/formatUtils.ts
> feat: add metrics value formatting by unit  @avivm

- .changeset/violet-rockets-tie.md
- app/src/renderer/apis/websockets/StompContext.tsx
- app/src/renderer/components/widget/card/HealthStatusDashboardWidget.tsx
> fix: slowness when navigating from instance dashboard to another page

- .changeset/nine-cougars-turn.md
- daemon/src/main/kotlin/dev/krud/boost/daemon/backup/ro/BackupDTO.kt
- daemon/src/test/kotlin/dev/krud/boost/daemon/backup/BackupExporterTest.kt
- daemon/src/test/kotlin/dev/krud/boost/daemon/configuration/folder/_stubs.kt
> fix: add missing sort when exporting folders

- daemon/src/main/kotlin/dev/krud/boost/daemon/backup/SystemBackupService.kt
- daemon/src/test/kotlin/dev/krud/boost/daemon/backup/SystemBackupServiceTest.kt
Closes #587 
Part of the auto backups feature, no changeset needed
> feat: avoid creating empty auto backups

- app/src/renderer/layout/common/main-sidebar/navbar/SettingsMenu.tsx
> feat: close settings page on escape press

- app/package.json
- app/windowsSign.js
Add signing logic for windows
Closes #404
> Fix windows code signing

- app/src/infra/daemon/packaged/packagedDaemon.ts
- app/src/main/main.ts
> fix: disable sentry on development builds

- daemon/src/test/kotlin/dev/krud/boost/daemon/actuator/model/BeansActuatorResponseTest.kt
- daemon/src/test/kotlin/dev/krud/boost/daemon/actuator/model/QuartzJobResponseTest.kt
> test: add bean response tests for empty objects

- app/src/renderer/hooks/useInstanceHealth.ts
> fix: instance health refresh loading status

- .changeset/tricky-turtles-drum.md
- daemon/src/main/kotlin/dev/krud/boost/daemon/actuator/model/EnvActuatorResponse.kt
- daemon/src/main/kotlin/dev/krud/boost/daemon/jackson/ToStringDeserializer.kt
- daemon/src/test/kotlin/dev/krud/boost/daemon/actuator/model/EnvActuatorResponseTest.kt
- daemon/src/test/kotlin/dev/krud/boost/daemon/jackson/ToStringDeserializerTest.kt
> Fix env value not being deserialized into string

- .changeset/poor-humans-film.md
- app/src/infra/autoupdate/appUpdater.ts
> fix: app updater quit and install not working 
